### ISSUE TITLE
Create documents for Simple POR jobs.

### ISSUE THREAD

**Issue by divyanka05** [cashflowy/docs#19]
***Create documents for the following Simple POR jobs:***
- [ ] [get_activities.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_activities.js) 
- [ ] [get_approvals.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_approvals.js)
- [ ] [get_budgets.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_budgets.js)
- [ ] [get_comments.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_comments.js)
- [ ] [get_documents.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_documents.js)
- [ ] [get_line_items.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_line_items.js)
- [ ] [get_members.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_members.js)
- [ ] [get_payment_schedules.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_payment_schedules.js)
- [ ] [get_pors.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_pors.js)
- [ ] [get_vendors.js](https://github.com/cashflowy/scripts-jobs/blob/main/scripts/gsheet/simplepor/get_vendors.js)

**Comment by alexjv89** [comment]
yes correct. 
document them and deploy them as well.
